### ISSUE TITLE
Enable `pytest` convention rules `PT` in ruff

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#278]
https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt

There are many ways to do the same thing in `pytest`, and I have found these rules to be helpful for consistency across a codebase. 

There are a few that are arguably too opinionated, in particular `PT003, PT004`, and `PT013`.

`PT006` can be configured with:
```TOML
[tool.ruff.lint.flake8-pytest-style]
parametrize-names-type = "csv"
```
for consistency with the existing codebase.
