### ISSUE TITLE
Consider `import-linter` or another way to document the overall architecture

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#282]
For new contributors, having some documentation of the overall `pins-python` package structure could be helpful.

In particular, it is helpful to get an idea of the dependency relationships between modules. [`import-linter`](https://github.com/seddonym/import-linter) allows you to [declare and enforce a layered architecture](https://import-linter.readthedocs.io/en/stable/contract_types.html#layers); for example for `pins-python`, the configuration could be declared as:

```TOML
[tool.importlinter]
root_packages = ["pins"]

[[tool.importlinter.contracts]]
name = "pins Modular Design"
type = "layers"
layers = [
    "constructors",
    "boards",
    "drivers",
    "meta | cache | rsconnect",
    "versions | utils",
    "config | errors | _types | data",
]
containers = "pins"
exhaustive = true
```

The idea is that that higher layers in the list can import from lower layers in the list, but not vice versa; and modules in the same level separated by `|` cannot import each other either.

Alternatively, I think having a diagram or other form of documentation would be quite helpful. However, `import-linter` has the advantage of enforcing the structure (potentially via `pre-commit`); whereas documentation can become out of date.
